#!/usr/bin/env python
# -*- coding: utf-8 -*-

"""
Each new term in the Fibonacci sequence is generated by adding the previous two
terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed
four million, find the sum of the even-valued terms.
"""

def fib(x):
	if x <= 1:
		return 1
	if x == 2:
		return 2
	return fib(x - 1) + fib(x - 2)

def main():
	x = 0
	f = 2
	i = 2
	while f < 4000000:
		if f % 2 == 0:
			x += f
		f = fib(i)
		i += 1
	print(x)

if __name__ == '__main__':
	main()